### ISSUE TITLE
签到指令报错，一言API网站证书过期

### ISSUE THREAD

**Issue by maoxig** [zhulinyv/nonebot_plugin_hoshino_sign#1]
第一次使用`签到`指令时bot无响应，控制台报错
![1684234107379](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/123555887/44e88028-2cc3-4451-af16-9ae86b2e0ae1)
![1684234107366](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/123555887/58a4ba05-2961-4cd1-adc8-cb6c04de19e3)
第二次发送时提示已经签过到了
检查发现是https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/blob/b62dd68429007c6f596af65171f1b16d689b3b5d/nonebot_plugin_hoshino_sign/__init__.py#L66-L68
中的api证书过期导致的
建议更换API，且网络IO时尽量使用try except捕获错误

**Comment by maoxig** [comment]
现在证书没过期了（

**Comment by zhulinyv** [comment]
已改。
