### ISSUE TITLE
自定义图片

### ISSUE THREAD

**Issue by 360add** [zhulinyv/nonebot_plugin_hoshino_sign#10]
现在这样有点刷屏

**Comment by zhulinyv** [comment]
> 现在这样有点刷屏

可是这样依旧是每次签到就会回复，并不会减少消息量。

**Comment by 360add** [comment]
是不会减少消息量，但是图片回复可以控制图片长宽大小占的区域，也可以把回复设计更美观，

**Comment by 360add** [comment]
![image](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/140232510/2675cebb-03c6-4645-b949-9c3917f0c8a4)
ru'guo如果大大愿意做我可以提供背景素材啥的，比如这种模板上面三角的改成圆的，放图鉴，下面文案改成签到回复，背景换成随机动漫图片啥的改的更好看

**Comment by 360add** [comment]
![image](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/140232510/d6cd6aa5-8d29-4baf-b7bf-0857c28363fb)
或者zhe'z这种的背景弄成动漫，下面加个框圆角框半透明模糊的效果放文案

**Comment by 360add** [comment]
图鉴可以改这种类似的二次元q版图片，更好看一些，这种图鉴我现在自己弄了一版在用，但是透明图好像是不行，背景会变乱码
![2](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/140232510/962dcb34-4270-4939-995e-6412d2cc28b1)

**Comment by 360add** [comment]
![image](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/140232510/d5f68af8-4af0-4aac-9aa6-9feadde1cd5c)
或者zhe'z这种长方形图片也可以

**Comment by zhulinyv** [comment]
> 图鉴可以改这种类似的二次元q版图片，更好看一些，这种图鉴我现在自己弄了一版在用，但是透明图好像是不行，背景会变乱码 ![2](https://user-images.githubusercontent.com/140232510/278498947-962dcb34-4270-4939-995e-6412d2cc28b1.png)

我加了配置项，可以自己配置图片目录，详细请看配置说明https://github.com/zhulinyv/nonebot_plugin_hoshino_sign#%EF%B8%8F-%E9%85%8D%E7%BD%AE

**Comment by zhulinyv** [comment]
> 是不会减少消息量，但是图片回复可以控制图片长宽大小占的区域，也可以把回复设计更美观，

我打开了一个新的 issue，关于回复问题的进度请移步，不过绘制图片比较麻烦，高三生没有时间 😭。
