### ISSUE TITLE
可以加个签到排行榜功能，输入排行榜可以查看本群图鉴收集前10名

### ISSUE THREAD

**Issue by 360add** [zhulinyv/nonebot_plugin_hoshino_sign#11]
可以加个签到排行榜功能，输入排行榜可以查看本群图鉴收集前10名，增加群友签到积极性

**Comment by zhulinyv** [comment]
我加了排行榜，和收集册在一起

**Comment by zhulinyv** [comment]
_Archived, if necessary, please reopen this issue._
