### ISSUE TITLE
图片回复

### ISSUE THREAD

**Issue by zhulinyv** [zhulinyv/nonebot_plugin_hoshino_sign#12]
是不会减少消息量，但是图片回复可以控制图片长宽大小占的区域，也可以把回复设计更美观，

_Originally posted by @360add in https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/issues/10#issuecomment-1782059305_

**Comment by 360add** [comment]
![9b5cc8dd8e0a499945fe8131cfb20a5128aec31d440fe-i0232H 拷贝](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/140232510/752d3e0b-2365-4e63-80d5-051a431cc2f5)
大大我弄了个大概的样子

**Comment by zhulinyv** [comment]
![image](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/66541860/58103632-042a-49c8-a58d-fb695aad3dac)
