### ISSUE TITLE
插件加载问题

### ISSUE THREAD

**Issue by PackageInstaller** [zhulinyv/nonebot_plugin_hoshino_sign#3]
我用的是zhenxun_bot,gitc lone的插件，加载插件报错，报错截图如下，删除__init__.py中第九行后能正常加载，能问问这一句是做什么的吗

![image](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/80018096/a97d5b00-29b2-4033-9412-7ff599d8613c)

**Comment by KaMmySuma** [comment]
> 我用的是zhenxun_bot,gitc lone的插件，加载插件报错，报错截图如下，删除__init__.py中第九行后能正常加载，能问问这一句是做什么的吗
> 
> ![image](https://user-images.githubusercontent.com/80018096/238686428-a97d5b00-29b2-4033-9412-7ff599d8613c.png)

这是加载另一个频道适配补丁插件，让bot能够响应频道中的签到指令。
如果不玩QQ频道可以删除。

**Comment by PackageInstaller** [comment]
感谢
