### ISSUE TITLE
签到指令正常运行但今日一言报错。

### ISSUE THREAD

**Issue by CaffuChin0** [zhulinyv/nonebot_plugin_hoshino_sign#5]
![QQ截图20230518092227](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/47897127/58808c40-1ce4-4b90-9633-17e2dcdb624e)

控制台无报错
![{_YBGWY}FNPIANO601GKLZC](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/47897127/13f86989-e1aa-4b13-b8df-951125b02b37)
![Y ` FFQ4~RY%1J@0FF`3DPA](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/47897127/ec4f5ac5-b74c-40d8-bdeb-de4d5dc2f074)

系统：Ubuntu
真寻版本：v0.1.6.6
插件版本：应该是最新的吧

**Comment by zhulinyv** [comment]
已改。
