### ISSUE TITLE
[BUG] 一言接口出错导致nb服务器ip暴露

### ISSUE THREAD

**Issue by KroMiose** [zhulinyv/nonebot_plugin_hoshino_sign#6]
![image](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/57167362/cf4971b7-0a2f-4b72-91b8-dc579d5e5563)

服务器访问一言接口时如果被拒绝回返回服务器ip，并且直接输出到聊天窗口，建议针对进行处理

https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/blob/a67c8bd19805085ef88ba432827973b3e39c3003/nonebot_plugin_hoshino_sign/__init__.py#L76-L82

**Comment by zhulinyv** [comment]
已修
