### ISSUE TITLE
签到报错

### ISSUE THREAD

**Issue by annko11** [zhulinyv/nonebot_plugin_hoshino_sign#7]
签到有时报错，bot无回应，第二次签提示已签到过
![屏幕截图 2023-07-10 080225](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/139084066/008d0d17-5325-4ba8-b470-204304279216)

**Comment by zhulinyv** [comment]
插件版本？

**Comment by annko11** [comment]
> 插件版本？

是前两天下载的，应该是最新版的

**Comment by zhulinyv** [comment]
> > 插件版本？
> 
> 是前两天下载的，应该是最新版的

**无法复现问题捏...**

请确认插件版本为最新(使用镜像源可能会导致插件不是最新)。

如果问题依旧，请尝试声明全局变量 `global response_text`

![image](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/66541860/dd91dc84-285d-4807-8e30-af49fcd3a5b9)

**Comment by annko11** [comment]
> 
我用的是镜像源下载的，可能确实是版本问题，感谢
